### ISSUE TITLE
Kali rolling?

### ISSUE THREAD

**Issue by Apadgett879** [kimocoder/wifite-ng#2]
Hi, I was wondering if this is the version that is supplied in kali linux (rolling release)

**Comment by kimocoder** [comment]
Yes, this is a working version of wifite (by derv82), Kali is using a outdated version which are more or less broken. This works :)

Original sourcecode @ https://github.com/derv82/wifite

**Comment by Apadgett879** [comment]
May I suggest trying to get this version into the kali repos?

**Comment by kimocoder** [comment]
I allready tried, reporting it @ bugs.kali.org

**Comment by Apadgett879** [comment]
perhaps drop into their IRC channel

**Comment by kimocoder** [comment]
I'm there too :) will do some tries with time. Also have too look at the "no capture file" issue which was reported today.
